pub const RATELIMIT_SELECTOR_HEADER_KEY: &str = "x-curve -ratelimit-selector";
pub const SYSTEM_ROLE: &str = "system";
pub const USER_ROLE: &str = "user";
pub const TOOL_ROLE: &str = "tool";
pub const ASSISTANT_ROLE: &str = "assistant";
pub const CURVE_FC_REQUEST_TIMEOUT_MS: u64 = 120000; // 2 minutes
pub const MODEL_SERVER_NAME: &str = "server";
pub const CURVE_ROUTING_HEADER: &str = "x-curve -llm-provider";
pub const MESSAGES_KEY: &str = "messages";
pub const CURVE_PROVIDER_HINT_HEADER: &str = "x-curve -llm-provider-hint";
pub const CHAT_COMPLETIONS_PATH: &str = "/v1/chat/completions";
pub const HEALTHZ_PATH: &str = "/healthz";
pub const CURVE_STATE_HEADER: &str = "x-curve -state";
pub const CURVE_FC_MODEL_NAME: &str = "Curve-Function-1.5B";
pub const REQUEST_ID_HEADER: &str = "x-request-id";
pub const TRACE_PARENT_HEADER: &str = "traceparent";
pub const CURVE_INTERNAL_CLUSTER_NAME: &str = "curve _internal";
pub const CURVE_UPSTREAM_HOST_HEADER: &str = "x-curve -upstream";
pub const CURVE_MODEL_PREFIX: &str = "Curve";
pub const HALLUCINATION_TEMPLATE: &str =
    "It seems I'm missing some information. Could you provide the following details ";
pub const OTEL_COLLECTOR_HTTP: &str = "opentelemetry_collector_http";
pub const OTEL_POST_PATH: &str = "/v1/traces";
